### ISSUE TITLE
Is there an Linux/Ubuntu program?

### ISSUE THREAD

**Issue by Bluppie** [Den-W/PwKeeper#1]
I am using Ubuntu and like to have an program that can be used on my Ubuntu laptop with Ubuntu 16.04 LTS.

Is it possible to use your device on multiple os? Like Linux, Android and so on?

Thanks for your effort.

**Comment by Den-W** [comment]
Hi!
Yes, you may use it with any platform.
Generally speaking, PwKeeper is just a keyboard with configurable sequences.
So, I think, it will run with any device that understands USB keyboard.
You need to load your sequences of keys into it - that's all.

The only disadvantage - right now config program is windows-only. 
You may try to launch it from under WinE. A virtual COM port used for communication between PwKeeper and PwKeeperPc. But I don't know how it will work.
It is possible to add simple COM-accessible text console for configuring token. If there would be some requests from public  for this feature - I may add it.
