### ISSUE TITLE
Работа клавиатуры на уровне bios

### ISSUE THREAD

**Issue by me11ved** [Den-W/PwKeeper#2]
Добрый день, есть зашифрованный диск с помощью программы truecrypt, при запуски пк нужно вводить пароль. 

Вопросы:

- Может ли данное устройство вводить пароль на уровне bios?
- Если да, не будет ли конфликтов с usb клавиатурой подключенной к пк?

Спасибо

**Comment by Den-W** [comment]
Добрый день,

Этот токен со стороны компа виден как USB клавиатура .
Если биос работает с USB клавиатурой - то и с токеном будет.
Конфликтов не будет - к компу можно подключить несколько клавиатур - и все они будут работать параллельно.
Токен - это просто еще одна клавиатура.

Есть подводные камушки:

1) Токен , по сути, посылает нажатия кнопок.
Пока идет латинский алфавит - все хорошо.
Но если вы захотите ввести русский текст - надо будет послать коды для переключения языка.
В описании есть команды нажатий Ctrl, Shift, Alt - итд (например одновременное нажатие Ctrl-Alt-Del).
Коды переключения на разных компах могут быть разные (Ctrl-Shift,Alt-Shift)

2) В проекте лежит полностью рабочий бинарник и исходник ino.
Но чтобы исходник после сборки правильно отображал русские буквы нужно подправить библиотеку u8g2. Может с новой версией u8g2 и так все работать будет. а может и нет.
Если на токене будут крокозябры - нужно смотреть процедуру трансляции русских букв в фонт.

**Comment by me11ved** [comment]
Спасибо за оперативный ответ.

Кириллицы в пароли нет.

После ввода нужно нажимать Enter - это я как понимаю реализовано?

Тикет можно закрывать

**Comment by Den-W** [comment]
Да 
Enter это такая же кнопка, что и остальные.
Посмотрите в файле примеров - там все это есть.
типовой сценарий: CtrlAltDel-Имя-Tab-Пароль-Enter
